CREATE DATABASE UNIVERSITY_REGISTRY;
USE UNIVERSITY_REGISTRY;
CREATE TABLE STUDENT (
Fname VARCHAR(255),
Minit CHAR(1),
Lname VARCHAR(255),
SCHOOL_ID CHAR(9) NOT NULL PRIMARY KEY,
BIRTH_DATE DATE,
Address VARCHAR(255),
Sex CHAR(1),
GRADYEAR INT,
FIELD_OF_STUDY VARCHAR(255),
NUMBER_OF_CLASSES INT,
COURSE_ID INT,
);

CREATE TABLE COURSE (
SUBJECT_ VARCHAR(255),
COST INT,
TIME_ VARCHAR(255),
COURSE_INFO VARCHAR(255),
COURSE_ID INT NOT NULL PRIMARY KEY,
);

CREATE TABLE TEACHER (
DEGREE VARCHAR(255),
TEACHES VARCHAR(255),
COURSE_ID INT, 
Fname VARCHAR(255),
MINIT VARCHAR(1),
Lname VARCHAR(255),
DEPARTMENT_NUMBER INT,
TEACHER_ID VARCHAR(255),
DIRECTOR VARCHAR(255),

);

CREATE TABLE DEPARTMENT (
DIRECTOR VARCHAR(255),
DEPARTMENT_NUMBER INT,
FIELD_OF_STUDY VARCHAR(255),
DIRECTOR_ID VARCHAR(255),
TEACHER_ID VARCHAR(255),
);